sudo: required
services:
  - docker

#before testing or deploying
before_install:
  - docker build -t beoboe/docker-react -f Dockerfile.dev .

# to run tests
script:
# the -e CI=true is to ensure that the run command return anything not just sleeping there
# we could append -- --coverage
  - docker run -e CI=true beoboe/docker-react npm run test

deploy:
  provider: "elasticbeanstalk"
  region: "eu-north-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-021660495013"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
